"""Add data modeling tables

Revision ID: ca493cd501f4
Revises: a6a7a3657b13
Create Date: 2026-03-31 09:11:14.725776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca493cd501f4'
down_revision = 'a6a7a3657b13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculated_columns',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('data_type', sa.Enum('NUMBER', 'CURRENCY', 'PERCENTAGE', 'TEXT', 'DATE', 'DATETIME', 'BOOLEAN', name='datatype'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculated_columns_column_name'), 'calculated_columns', ['column_name'], unique=False)
    op.create_index(op.f('ix_calculated_columns_dataset_id'), 'calculated_columns', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_calculated_columns_user_id'), 'calculated_columns', ['user_id'], unique=False)
    op.create_table('hierarchies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hierarchy_type', sa.Enum('DATE', 'GEOGRAPHIC', 'CUSTOM', name='hierarchytype'), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hierarchies_dataset_id'), 'hierarchies', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_hierarchies_name'), 'hierarchies', ['name'], unique=False)
    op.create_index(op.f('ix_hierarchies_user_id'), 'hierarchies', ['user_id'], unique=False)
    op.create_table('measures',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('formula_display', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Enum('NUMBER', 'CURRENCY', 'PERCENTAGE', 'TEXT', 'DATE', 'DATETIME', 'BOOLEAN', name='datatype'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measures_dataset_id'), 'measures', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_measures_name'), 'measures', ['name'], unique=False)
    op.create_index(op.f('ix_measures_user_id'), 'measures', ['user_id'], unique=False)
    op.create_table('relationships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('from_dataset_id', sa.UUID(), nullable=False),
    sa.Column('to_dataset_id', sa.UUID(), nullable=False),
    sa.Column('from_column', sa.String(length=255), nullable=False),
    sa.Column('to_column', sa.String(length=255), nullable=False),
    sa.Column('cardinality', sa.Enum('ONE_TO_ONE', 'ONE_TO_MANY', 'MANY_TO_ONE', 'MANY_TO_MANY', name='cardinalitytype'), nullable=True),
    sa.Column('direction', sa.Enum('SINGLE', 'BOTH', name='relationshipdirection'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['to_dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_from_dataset_id'), 'relationships', ['from_dataset_id'], unique=False)
    op.create_index(op.f('ix_relationships_to_dataset_id'), 'relationships', ['to_dataset_id'], unique=False)
    op.create_index(op.f('ix_relationships_user_id'), 'relationships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_user_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_to_dataset_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_dataset_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_measures_user_id'), table_name='measures')
    op.drop_index(op.f('ix_measures_name'), table_name='measures')
    op.drop_index(op.f('ix_measures_dataset_id'), table_name='measures')
    op.drop_table('measures')
    op.drop_index(op.f('ix_hierarchies_user_id'), table_name='hierarchies')
    op.drop_index(op.f('ix_hierarchies_name'), table_name='hierarchies')
    op.drop_index(op.f('ix_hierarchies_dataset_id'), table_name='hierarchies')
    op.drop_table('hierarchies')
    op.drop_index(op.f('ix_calculated_columns_user_id'), table_name='calculated_columns')
    op.drop_index(op.f('ix_calculated_columns_dataset_id'), table_name='calculated_columns')
    op.drop_index(op.f('ix_calculated_columns_column_name'), table_name='calculated_columns')
    op.drop_table('calculated_columns')
    # ### end Alembic commands ###
